name: CI

permissions: write-all

on:
  pull_request:
    paths:
      - TEST.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Script
        uses: actions/github-script@v6.4.1
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              team_reviewers: ["orange-likers"]
            });
